#pragma once

#include <Arduino.h>

extern const unsigned char button_bitmap_1[] PROGMEM;
extern const unsigned char button_bitmap_2[] PROGMEM;
extern const unsigned char button_bitmap_3[] PROGMEM;
extern const unsigned char button_bitmap_4[] PROGMEM;
extern const unsigned char button_bitmap_5[] PROGMEM;
extern const unsigned char button_bitmap_6[] PROGMEM;
extern const unsigned char button_bitmap_7[] PROGMEM;
extern const unsigned char button_bitmap_8[] PROGMEM;
extern const int button_bitmap_count;
extern const unsigned char* button_bitmap_array[8];
extern const unsigned char gun_bitmap_1[] PROGMEM;
extern const unsigned char gun_bitmap_2[] PROGMEM;
extern const unsigned char gun_bitmap_3[] PROGMEM;
extern const unsigned char gun_bitmap_4[] PROGMEM;
extern const unsigned char gun_bitmap_5[] PROGMEM;
extern const unsigned char gun_bitmap_6[] PROGMEM;
extern const unsigned char gun_bitmap_7[] PROGMEM;
extern const unsigned char gun_bitmap_8[] PROGMEM;
extern const int gun_bitmap_count;
extern const unsigned char* gun_bitmap_array[12];
extern const unsigned char sword_bitmap_1[] PROGMEM;
extern const unsigned char sword_bitmap_2[] PROGMEM;
extern const unsigned char sword_bitmap_3[] PROGMEM;
extern const unsigned char sword_bitmap_4[] PROGMEM;
extern const unsigned char sword_bitmap_5[] PROGMEM;
extern const unsigned char sword_bitmap_6[] PROGMEM;
extern const unsigned char sword_bitmap_7[] PROGMEM;
extern const unsigned char sword_bitmap_8[] PROGMEM;
extern const unsigned char sword_bitmap_9[] PROGMEM;
extern const unsigned char sword_bitmap_10[] PROGMEM;
extern const int sword_bitmap_count;
extern const unsigned char* sword_bitmap_array[15];
extern const unsigned char kick_bitmap_1[] PROGMEM;
extern const unsigned char kick_bitmap_2[] PROGMEM;
extern const unsigned char kick_bitmap_3[] PROGMEM;
extern const unsigned char kick_bitmap_4[] PROGMEM;
extern const unsigned char kick_bitmap_5[] PROGMEM;
extern const unsigned char kick_bitmap_7[] PROGMEM;
extern const unsigned char kick_bitmap_6[] PROGMEM;
extern const unsigned char kick_bitmap_8[] PROGMEM;
extern const int kick_bitmap_count;
extern const unsigned char* kick_bitmap_array[9];
extern const unsigned char eat_bitmap_2[] PROGMEM;
extern const unsigned char eat_bitmap_1[] PROGMEM;
extern const unsigned char eat_bitmap_3[] PROGMEM;
extern const unsigned char eat_bitmap_4[] PROGMEM;
extern const unsigned char eat_bitmap_5[] PROGMEM;
extern const unsigned char eat_bitmap_7[] PROGMEM;
extern const unsigned char eat_bitmap_6[] PROGMEM;
extern const unsigned char eat_bitmap_8[] PROGMEM;
extern const int eat_bitmap_count;
extern const unsigned char* eat_bitmap_array[10];
extern const unsigned char throw_bitmap_1[] PROGMEM;
extern const unsigned char throw_bitmap_2[] PROGMEM;
extern const unsigned char throw_bitmap_3[] PROGMEM;
extern const unsigned char throw_bitmap_4[] PROGMEM;
extern const unsigned char throw_bitmap_5[] PROGMEM;
extern const unsigned char throw_bitmap_6[] PROGMEM;
extern const unsigned char throw_bitmap_7[] PROGMEM;
extern const unsigned char throw_bitmap_8[] PROGMEM;
extern const int throw_bitmap_count;
extern const unsigned char* throw_bitmap_array[12];
extern const unsigned char bale_bitmap_1[] PROGMEM;
extern const unsigned char bale_bitmap_2[] PROGMEM;
extern const unsigned char bale_bitmap_3[] PROGMEM;
extern const unsigned char bale_bitmap_4[] PROGMEM;
extern const unsigned char bale_bitmap_5[] PROGMEM;
extern const unsigned char bale_bitmap_6[] PROGMEM;
extern const int bale_bitmap_count;
extern const unsigned char* bale_bitmap_array[9];